---
title: "Beer Case Study App"
author: "Ahmed Awadallah"
date: "1/16/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Beer Case Study Rshiny App

### Summary

This app allows you to play with US brewery data. It allows the user to see boxplots, histograms, and scatter plots of all the data or by state.

### [Link To Site](https://ahmedawadallah.shinyapps.io/rshinyapp/)

### User Guide

* Histogram Bin Slider
  + This allows the user to select how much data per Bin
  + Limited from 1 to 50 bins
  + Only interacts with histogram plots
* Data Selection
  + This allows the user to select what current data setup is being analyzed
  + ABV/IBU displays histograms by default
  + IBU v ABV displays scatter plot by default
* State Selection
  + This allows the user to select data that either pertains to the whole data set (Selecting ALL) or a specific state
  + Includes all 50 US states and Washington D.C.
* Plot Selection
  + Only works when the data is ABV or IBU
  + Allows the user to select either histograms or boxplots
* Overlay Linear Model
  + Only works when the data is IBU v ABV
  + Allows user to display a linear model on IBU v ABV scatter plots
