<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />



<meta name="date" content="2021-12-27" />

<title>Exploration and Analysis of US Beers and Breweries</title>

<script src="site_libs/header-attrs-2.11/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/bootstrap.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>








<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.tab('show');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->




</head>

<body>


<div class="container-fluid main-container">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">My Website</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">Home</a>
</li>
<li>
  <a href="case_study_01.html">Beer Study</a>
</li>
<li>
  <a href="app_page.html">Beer Study App</a>
</li>
<li>
  <a href="CaseStudy2_with_code.html">Employee Study</a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">



<h1 class="title toc-ignore">Exploration and Analysis of US Beers and Breweries</h1>
<h4 class="date">12/27/2021</h4>

</div>


<div id="executive-summary-introduction" class="section level2">
<h2>Executive Summary &amp; Introduction</h2>
<p>Beer and brewery location data was provided to us for a number of craft breweries in the United States. We combined this data and performed several exploratory data analysis procedures, which are presented below. Through the analysis, we have found a statistically significant difference between IBU values in the West and Midwest regions, and have also identified a potential new market for German beers.</p>
</div>
<div id="setup" class="section level1">
<h1>Setup</h1>
<div id="load-libraries" class="section level2">
<h2>Load Libraries</h2>
</div>
<div id="set-global-parameters" class="section level2">
<h2>Set Global Parameters</h2>
<pre class="r"><code>knit_print.data.frame &lt;- lemon_print</code></pre>
</div>
<div id="load-datasets" class="section level2">
<h2>Load Datasets</h2>
<pre class="r"><code># load brewery data CSV file
brew &lt;- read.csv(&#39;Breweries.csv&#39;, encoding = &#39;UTF-8&#39;) %&gt;% 
  # trim white space around the state abbreviation
  mutate(State=str_trim(State))

# load beer data from CSV file
beer &lt;- read.csv(&#39;Beers.csv&#39;,  encoding = &#39;UTF-8&#39;)

# load city, state geolocation data from csv file
cities &lt;- read.csv(&#39;Cities.csv&#39;) %&gt;% select(-COUNTY) %&gt;%
  rename(CITY_LAT=LATITUDE, CITY_LON=LONGITUDE)

# merge beer and brewery datasets
bb = merge(beer, brew, by.x =&quot;Brewery_id&quot;, by.y = &quot;Brew_ID&quot;)

colnames(bb)[2] = &quot;Beer_Name&quot;
colnames(bb)[8] = &quot;Brewery_Name&quot;

theme_set(theme_classic())

# create train-test splitting function
train_test_split = function(df, splitPerc){
  # Function that splits dataframe into a training set and test set based on specified split proportion
  # Params:
    # df: (data.frame) Raw dataframe that will be split
    # splitPerc: (int) Percentage of raw data to be placed into training set
  # Output
    # (list) Returns a list of two dataframe objects. First one being the training set and second test set
  trainIndices = sample(1:dim(df)[1], round(splitPerc * dim(df)[1]))
  train = df[trainIndices,]
  test = df[-trainIndices,]
  return(list(train, test))
}</code></pre>
</div>
</div>
<div id="initial-exploratory-data-analysis" class="section level1">
<h1>Initial Exploratory Data Analysis</h1>
<div id="breweries-per-state" class="section level2">
<h2>Breweries Per State</h2>
<p>How many breweries are present in each state?</p>
<pre class="r"><code># change the state column from a &lt;chr&gt; to a &lt;fctr&gt; and count the breweries
breweries_by_state &lt;- bb %&gt;% 
  group_by(State) %&gt;%
  summarize(n=n_distinct(Brewery_Name))

# create bar chart of breweries by state
breweries_by_state %&gt;%
  ggplot(aes(x=reorder(State, n), y=n)) +
    # add lines for lollipop chart
    geom_segment(aes(xend=State, yend=0), color=&#39;#bdc3c7&#39;) +
    # add points for lollipop chart
    geom_point(size=3, color=&#39;#DD1731&#39;) +
    # flip bars from x to y axis
    coord_flip() +
    # add title, x-axis, and y-axis label 
    labs(x=&#39;&#39;, y=&#39;&#39;, title=&#39;Number of Breweries by State&#39;) +
    # remove background and format text
    theme(
      panel.background = element_blank(),
      panel.grid.major=element_blank(),
      panel.grid.minor=element_blank(),
      plot.title = element_text(size=28, color=&#39;#DD1731&#39;),
      axis.text=element_text(size=12),
      axis.title=element_text(size=20)
    )</code></pre>
<p><img src="case_study_01_files/figure-html/brew_count-1.png" width="672" /></p>
<p>The state with the most breweries is Colorado with a count of 46, followed by California with 39. The states with the least number of breweries are Washington DC, North Dakota, South Dakota, and West Virginia, with only 1 each.</p>
</div>
<div id="address-the-missing-values" class="section level2">
<h2>Address the Missing Values</h2>
<p>To address the missing values, we first need to find which columns have missing values.</p>
<pre class="r"><code># display any NA values across all features
bb %&gt;%  
  summarise(across(everything(), ~ sum(is.na(.x)))) %&gt;%
  gather(Column, NA_Count) %&gt;%
  ggplot(aes(x=NA_Count, y=Column, fill = Column)) + 
  geom_col(fill=&#39;#DD1731&#39;) + 
  labs(
    title=&#39;Percentages of Missing Values&#39;, 
    y=&#39;Column Name&#39;, 
    x=&#39;Number of Missing Values&#39;
  ) +
  # remove background and format text
  theme(
    legend.position = &#39;none&#39;,
    plot.title = element_text(size=18, color=&#39;#DD1731&#39;),
    panel.background = element_blank(),
    panel.grid.major=element_blank(),
    panel.grid.minor=element_blank(),
  ) </code></pre>
<p><img src="case_study_01_files/figure-html/na_check-1.png" width="672" /></p>
<p>Only the ABV and IBU columns have missing values. In this case, we will remove them from further analysis.</p>
<pre class="r"><code># only ABV missing values removed
bb_clean_ABV &lt;- bb %&gt;% filter(!is.na(ABV))

# only IBU missing values removed
bb_clean_IBU &lt;- bb %&gt;% filter(!is.na(IBU))

# both ABV and IBU missing values removed
bb_clean &lt;- bb %&gt;% filter(!is.na(ABV) &amp; !is.na(IBU))</code></pre>
<p>To analyze the data, we made multiple copies of the datasets for situations where we analyze only IBU, only ABV, or a combination of IBU and ABV.</p>
</div>
<div id="median-abv-and-ibu-comparison-by-state" class="section level2">
<h2>Median ABV and IBU Comparison by State</h2>
<p>Compute the median ABV and IBU for each state and compare the results using a bar chart.</p>
<pre class="r"><code># calculate median values by state and store in dataframe
med_ABV = bb_clean_ABV %&gt;%
  group_by(State)%&gt;% 
  summarise(MedianABV=median(ABV))

med_IBU = bb_clean_IBU %&gt;%
  group_by(State)%&gt;% 
  summarise(MedianIBU=median(IBU))

# start with the cleaned dataframe
bb_clean %&gt;% 
  # group by the state
  group_by(State) %&gt;%
  # add statistics for the median ABV and median IBU
  summarize(&#39;ABV (Median)&#39;=median(ABV), &#39;IBU (Median)&#39;=median(IBU)) %&gt;% 
  # gather new columns into key-value pairs
  gather(statistic, val, c(&#39;ABV (Median)&#39;, &#39;IBU (Median)&#39;)) %&gt;%
  # create plot to compare median ABV and IBU values between states
  ggplot(aes(x=reorder(State, val), y=val)) +
    # add bar geometry to the plot
    # geom_bar(stat=&#39;identity&#39;, fill=&#39;#DD1731&#39;, width=0.6, alpha=0.8) +
    # add lines for lollipop chart
    geom_segment(aes(xend=State, yend=0), color=&#39;#bdc3c7&#39;) +
    # add points for lollipop chart
    geom_point(size=3, color=&#39;#DD1731&#39;) +
    # flip the bars to be horizontal
    coord_flip() + 
    # create separate facets for the measurements
    facet_wrap(~statistic, nrow=1, scales=&#39;free&#39;) +
    # remove background and format text
    theme(
      legend.position = &#39;none&#39;,
      plot.title = element_text(size=24, color=&#39;#DD1731&#39;),
      panel.background = element_blank(),
      panel.grid.major=element_blank(),
      panel.grid.minor=element_blank(),
      axis.text=element_text(size=12),
      axis.title=element_text(size=20)
    ) +
    # add plot title, x, and y labels
    labs(
      title=&#39;Median ABV and IBU by State&#39;,
      x=&#39;State&#39;,
      y=&#39;Measurement Value&#39;
    )</code></pre>
<p><img src="case_study_01_files/figure-html/median_ABV_IBU_01-1.png" width="672" /></p>
<div id="median-abv-results" class="section level3">
<h3>Median ABV Results</h3>
<p>The states with the largest median ABV value are Kentucky and Washington DC with a value of 0.0625. Utah has the lowest median ABV with a value of 0.04.</p>
</div>
<div id="median-ibu-results" class="section level3">
<h3>Median IBU Results</h3>
<p>The state with the largest median IBU is Maine with a value of 61. Wisconsin has the lowest median IBU with a value of 19.</p>
</div>
</div>
<div id="max-abv-and-ibu" class="section level2">
<h2>Max ABV and IBU</h2>
<p>Calculate the maximum ABV and IBU for each state and store the results in a new dataset.</p>
<pre class="r"><code># set a constant for the graphical display
n &lt;- 12

# find the maximum ABV and IBU values for each state and store in dataframe
max_ABV = bb_clean_ABV %&gt;%
  group_by(State)%&gt;% 
  summarise(MaxABV=max(ABV))

max_IBU = bb_clean_IBU %&gt;%
  group_by(State)%&gt;% 
  summarise(MaxIBU=max(IBU))

max_ABV %&gt;% arrange(desc(MaxABV))</code></pre>
<pre><code>## # A tibble: 51 x 2
##    State MaxABV
##    &lt;chr&gt;  &lt;dbl&gt;
##  1 CO     0.128
##  2 KY     0.125
##  3 IN     0.12 
##  4 NY     0.1  
##  5 CA     0.099
##  6 ID     0.099
##  7 MA     0.099
##  8 ME     0.099
##  9 MI     0.099
## 10 MN     0.099
## # ... with 41 more rows</code></pre>
<div id="display-max-abv-states" class="section level3">
<h3>Display Max ABV States</h3>
<p>The state with the largest maximum ABV is Colorado with a value of 0.128. The state with the smallest maximum ABV is Delaware with a value of 0.055.</p>
<pre class="r"><code># plot maximum ABV by state
max_ABV %&gt;% 
  arrange(desc(MaxABV)) %&gt;% head(n) %&gt;%
  ggplot(aes(x=reorder(State, MaxABV), y=MaxABV)) +
    geom_bar(stat=&#39;identity&#39;, fill=&#39;#DD1731&#39;, width=0.6) +
    gghighlight(State == &#39;CO&#39;) +
    # flip the bars to be horizontal
    coord_flip() +
    # remove background and format text
    theme(
      plot.title = element_text(size=22, color=&#39;#DD1731&#39;),
      panel.background = element_blank(),
      panel.grid.major=element_blank(),
      panel.grid.minor=element_blank(),
      axis.text=element_text(size=12),
      axis.title=element_text(size=20)
    ) +
    # add plot title, x, and y labels
    labs(
      title=paste(&#39;Top&#39;, n, &#39;Maximum ABV Values by State&#39;, sep=&#39; &#39;),
      x=&#39;State&#39;,
      y=&#39;ABV (Max.)&#39;
    )</code></pre>
<p><img src="case_study_01_files/figure-html/max_ABV_IBU_02-1.png" width="672" /></p>
</div>
<div id="display-max-abv-states-1" class="section level3">
<h3>Display Max ABV States</h3>
<p>The State with the largest max IBU is Oregon with a value of 138. The state with the smallest max IBU is Arkansas.</p>
<pre class="r"><code># plot maximum ABV by state
max_IBU %&gt;% 
  arrange(desc(MaxIBU)) %&gt;% head(n) %&gt;%
  ggplot(aes(x=reorder(State, MaxIBU), y=MaxIBU)) +
    geom_bar(stat=&#39;identity&#39;, fill=&#39;#DD1731&#39;, width=0.6) +
    gghighlight(State == &#39;OR&#39;) +
    # flip the bars to be horizontal
    coord_flip() +
    # remove background and format text
    theme(
      plot.title = element_text(size=22, color=&#39;#DD1731&#39;),
      panel.background = element_blank(),
      panel.grid.major=element_blank(),
      panel.grid.minor=element_blank(),
      axis.text=element_text(size=12),
      axis.title=element_text(size=20)
    ) +
    # add plot title, x, and y labels
    labs(
      title=paste(&#39;Top&#39;, n, &#39;Maximum IBU Values by State&#39;, sep=&#39; &#39;),
      x=&#39;State&#39;,
      y=&#39;IBU (Max.)&#39;
    )</code></pre>
<p><img src="case_study_01_files/figure-html/max_ABV_IBU_03-1.png" width="672" /></p>
</div>
</div>
<div id="statistical-summary-of-abv-data" class="section level2">
<h2>Statistical Summary of ABV Data</h2>
<p>We will analyze the ABV values of all beers using a statistical summary, boxplot, and histogram.</p>
<pre class="r"><code># calculate summary statistics for ABV values
summary(bb_clean$ABV)</code></pre>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
## 0.02700 0.05000 0.05700 0.05991 0.06800 0.12500</code></pre>
<pre class="r"><code># create boxplot of ABV values
bb_clean %&gt;% 
  ggplot(aes(x=ABV)) +     
  geom_boxplot(color=&#39;#2d3436&#39;, fill=&#39;#DD1731&#39;) +
    # remove background and format text
    theme(
      plot.title = element_text(size=16, color=&#39;#DD1731&#39;),
      panel.background = element_blank(),
      panel.grid.major=element_blank(),
      panel.grid.minor=element_blank(),
      axis.text=element_text(size=11),
      axis.title=element_text(size=14)
    ) +
    # add plot title, x, and y labels
    labs(
      title=paste(&#39;Boxplot of ABV in Craft Beers&#39;),
      x=&#39;ABV&#39;,
      y=&#39;Count&#39;
    )</code></pre>
<p><img src="case_study_01_files/figure-html/abv_stats-1.png" width="672" /></p>
<pre class="r"><code># create histogram of ABV values
bb_clean %&gt;% 
  ggplot(aes(x=ABV)) + 
    geom_histogram(bins=30, color=&#39;white&#39;, fill=&#39;#DD1731&#39;) +
    # remove background and format text
    theme(
      plot.title = element_text(size=18, color=&#39;#DD1731&#39;),
      panel.background = element_blank(),
      panel.grid.major=element_blank(),
      panel.grid.minor=element_blank(),
      axis.text=element_text(size=12),
      axis.title=element_text(size=16)
    ) +
    # add plot title, x, and y labels
    labs(
      title=paste(&#39;Distribution of ABV in Craft Beers&#39;),
      x=&#39;ABV&#39;,
      y=&#39;Count&#39;
    )</code></pre>
<p><img src="case_study_01_files/figure-html/abv_stats-2.png" width="672" /></p>
<p>The ABV data is right skewed with mean at 0.05991 and 75% of the data is contained in the range of 0.050 to 0.068.</p>
</div>
<div id="the-relationship-between-bitterness-ibu-and-alcohol-content-abv" class="section level2">
<h2>The Relationship between Bitterness (IBU) and Alcohol Content (ABV)</h2>
<p>We will use a scatter plot to investigate if there is an apparent relationship between the bitterness of the beer and its alcoholic content.</p>
<pre class="r"><code># create a scatter plot of ABV and IBU
bb_clean %&gt;% ggplot(aes(x=ABV, y=IBU)) + 
  geom_point(position = &quot;jitter&quot;, size = 1, alpha=0.75, col = &quot;#DD1731&quot;) + 
  # remove background and format text
  theme(
    legend.position = &#39;none&#39;,
    plot.title = element_text(size=18, color=&#39;#DD1731&#39;),
    panel.background = element_blank(),
    panel.grid.major=element_blank(),
    panel.grid.minor=element_blank()
  ) + 
  # add axis titles
  labs(
    title=&#39;IBU vs ABV&#39;, 
    x=&#39;Alcohol by Volume (ABV)&#39;, 
    y=&#39;International Bitterness Units (IBU)&#39;,
  )</code></pre>
<p><img src="case_study_01_files/figure-html/abv_v_ibu_01-1.png" width="672" /></p>
<p>There does appear to be a positive linear relationship between ABV and IBU. After further statistical analysis there is overwhelming evidence to suggest that there is a positive linear relationship between ABV and IBU.(P &lt;2E-16). We are 95% confident that the population slope is contained in the interval (1244, 1320). The equation for the relationship is IBU = 1282*ABV - 34. Lastly, the R^2 for this relationship is 0.45 which means that ABV helps explain about 45% of the variation in IBU so, while there is a linear relationship present, it is not a strong linear relationship.</p>
<p>Below is a plot of the linear model.</p>
<pre class="r"><code># create a scatter plot of ABV and IBU with linear model
bb_clean %&gt;% ggplot(aes(x=ABV, y=IBU)) + 
  # add a jitter to the points to view overlapping data
  geom_jitter(size=1, alpha=0.75, color=&#39;#DD1731&#39;) + 
  # add a trend line to the data
  geom_smooth(formula=&#39;y~x&#39;, method=&#39;lm&#39;, color=&#39;#2c3e50&#39;) +
  # remove background and format text
  theme(
    legend.position = &#39;none&#39;,
    plot.title = element_text(size=18, color=&#39;#DD1731&#39;),
    panel.background = element_blank(),
    panel.grid.major=element_blank(),
    panel.grid.minor=element_blank()
  ) + 
  # add axis titles
  labs(
    title=&#39;IBU vs ABV with Linear Model Trendline&#39;, 
    x=&#39;Alcohol by Volume (ABV)&#39;, 
    y=&#39;International Bitterness Units (IBU)&#39;,
  )</code></pre>
<p><img src="case_study_01_files/figure-html/abv_v_ibu_02-1.png" width="672" /></p>
</div>
<div id="k-nearest-neighbors-knn-classification-using-abv-and-ibu" class="section level2">
<h2>K-Nearest-Neighbors (KNN) Classification using ABV and IBU</h2>
<p>The data was split into training, validation, and test sets in a 80/10/10 split. After some parameter tuning, we found the optimal K for this data set to be 23. The classification report for the model is shown below.</p>
<pre class="r"><code># The information on beer type is contained within the &quot;Style&quot; column
# We will Use regex to make two new data sets: one for IPA styles and one for 
# any other type of ale. Make sure that
# we are specifically selecting what we want. May involve some repetitive checking.
bb_ale = bb_clean %&gt;% 
  filter(
    str_detect(bb_clean$Style, regex(&quot;\\bale\\b&quot;, ignore_case = TRUE)) &amp; 
      !str_detect(bb_clean$Style, regex(&quot;\\bipa\\b&quot;, ignore_case = TRUE)))
bb_ipa = bb_clean %&gt;% 
  filter(str_detect(bb_clean$Style, regex(&quot;\\bipa\\b&quot;, ignore_case = TRUE)))

# add a new column in both dataframes specifying type
bb_ale = bb_ale %&gt;% mutate(AleType = &quot;NON IPA ALE&quot;)
bb_ipa = bb_ipa %&gt;% mutate(AleType = &quot;IPA&quot;)

# combine the dataframes
bb_ales = rbind(bb_ale, bb_ipa)

# set &quot;AleType&quot; column to be a factor
bb_ales$AleType = as.factor(bb_ales$AleType)

# select desired data
bb_knn = bb_ales %&gt;% select(ABV, IBU, AleType)

# specify features and targets for the KNN classifier
features = c(&quot;ABV&quot;, &quot;IBU&quot;)
target = c(&quot;AleType&quot;)

# normalize data Using z-score standardization
bb_knn_norm = bb_knn
bb_knn_norm$ABV = (bb_knn_norm$ABV - mean(bb_knn_norm$ABV))/sd(bb_knn_norm$ABV)
bb_knn_norm$IBU = (bb_knn_norm$IBU - mean(bb_knn_norm$IBU))/sd(bb_knn_norm$IBU)

# split Data
tt_l = train_test_split(bb_knn_norm, splitPerc = 0.9)
train_data = tt_l[[1]]
test_data = tt_l[[2]]
train_fea = train_data %&gt;% select(contains(features))
train_tar = train_data %&gt;% select(contains(target))
test_fea = test_data %&gt;% select(contains(features))
test_tar = test_data %&gt;% select(contains(target))

# train / test model
clsf_rep = knn(train_fea[,], test_fea[,], train_tar[,], k=23, prob = T)

# model analysis
CM_rep = confusionMatrix(table(clsf_rep, test_tar[,]))
CM_rep</code></pre>
<pre><code>## Confusion Matrix and Statistics
## 
##              
## clsf_rep      IPA NON IPA ALE
##   IPA          32           8
##   NON IPA ALE   7          47
##                                           
##                Accuracy : 0.8404          
##                  95% CI : (0.7505, 0.9078)
##     No Information Rate : 0.5851          
##     P-Value [Acc &gt; NIR] : 9.51e-08        
##                                           
##                   Kappa : 0.6725          
##                                           
##  Mcnemar&#39;s Test P-Value : 1               
##                                           
##             Sensitivity : 0.8205          
##             Specificity : 0.8545          
##          Pos Pred Value : 0.8000          
##          Neg Pred Value : 0.8704          
##              Prevalence : 0.4149          
##          Detection Rate : 0.3404          
##    Detection Prevalence : 0.4255          
##       Balanced Accuracy : 0.8375          
##                                           
##        &#39;Positive&#39; Class : IPA             
## </code></pre>
<p>The good performance of this model implies that there is a well defined clustered relationship between these two types of ale. Below is a plot visualizing the relationship.</p>
<pre class="r"><code># scatter plot with class color distinction
bb_knn_norm %&gt;% ggplot(aes(x=ABV, y=IBU, color=AleType)) + 
  geom_point() + 
    # remove background and format text
  theme(
    plot.title = element_text(size=18, color=&#39;#DD1731&#39;),
    panel.background = element_blank(),
    panel.grid.major=element_blank(),
    panel.grid.minor=element_blank()
  ) + 
  # add axis titles
  labs(
    title=&#39;IBU vs ABV Colored by Class&#39;, 
    x=&#39;Normalized Alcohol by Volume (ABV)&#39;, 
    y=&#39;Normalized International Bitterness Units (IBU)&#39;,
  )</code></pre>
<p><img src="case_study_01_files/figure-html/plot_of_clusters-1.png" width="672" /></p>
</div>
</div>
<div id="additional-exploratory-data-analysis---regional-variances" class="section level1">
<h1>Additional Exploratory Data Analysis - Regional Variances</h1>
<p>We will create additional data for brewery regions by manually labeling state to region relationships.</p>
<div id="create-region-feature" class="section level2">
<h2>Create Region Feature</h2>
<pre class="r"><code># create region vectors
west = c(&quot;WA&quot;, &quot;OR&quot;, &quot;CA&quot;, &quot;NV&quot;, &quot;UT&quot;, &quot;CO&quot;, &quot;WY&quot;, &quot;MT&quot;, &quot;ID&quot;)
midwest = c(&quot;ND&quot;, &quot;SD&quot;, &quot;NE&quot;, &quot;KS&quot;, &quot;MN&quot;, &quot;IA&quot;, &quot;MO&quot;, &quot;WI&quot;, &quot;MI&quot;, &quot;IL&quot;, &quot;IN&quot;, &quot;OH&quot;)
southwest = c(&quot;AZ&quot;, &quot;NM&quot;, &quot;OK&quot;, &quot;TX&quot;)
southeast = c(&quot;MD&quot;, &quot;DE&quot;, &quot;WV&quot;, &quot;VA&quot;, &quot;KY&quot;, &quot;TN&quot;, &quot;NC&quot;, &quot;SC&quot;, &quot;GA&quot;, &quot;AL&quot;, &quot;MS&quot;, &quot;AR&quot;, &quot;LA&quot;, &quot;FL&quot;, &quot;DC&quot;)
northeast = c(&quot;PA&quot;, &quot;NJ&quot;, &quot;NY&quot;, &quot;CT&quot;, &quot;RI&quot;, &quot;VT&quot;, &quot;MA&quot;, &quot;NH&quot;, &quot;ME&quot;)
hawaii_alaska = c(&quot;HI&quot;, &quot;AK&quot;)

# create a new ale dataframe with additional region feature
bb_clean_eda2_ales = bb_ales %&gt;%
  mutate(Region = case_when(
    is.element(State, west) ~ &quot;West&quot;,
    is.element(State, midwest) ~ &quot;Midwest&quot;,
    is.element(State, southwest) ~ &quot;Southwest&quot;,
    is.element(State, southeast) ~ &quot;Southeast&quot;,
    is.element(State, northeast) ~ &quot;Northeast&quot;,
    is.element(State, hawaii_alaska) ~ &quot;Other&quot;
  ))

#Ale Production Difference
bb_clean_eda2_ales %&gt;% 
  group_by(Region, AleType) %&gt;%
  summarise(AleType_Count = n()) %&gt;%
  ggplot(aes(x = Region, y = AleType_Count, fill=AleType)) + 
  geom_col(position=&quot;dodge&quot;) + 
  ylab(&quot;Ale Type Count&quot;) + ggtitle(&quot;Ale Type Count by Region&quot;)</code></pre>
<pre><code>## `summarise()` has grouped output by &#39;Region&#39;. You can override using the `.groups` argument.</code></pre>
<p><img src="case_study_01_files/figure-html/custom_eda_01-1.png" width="672" /></p>
<p>To further expand on the ale type analysis briefly here is the production count by region for IPA versus non IPA ales. Most regions appear to prefer more of the non IPA ales but the north east region is the one exception where IPA is ahead by just a bit.</p>
<p>Earlier we looked into the distribution of ABV and IBU across the entire data set but now we will do a similar analysis by region. The plan is to do an analysis of variance across all regions to see if there distributions are all the same or if there is evidence of a difference.</p>
<pre class="r"><code># create a new dataframe with the &quot;bb_clean&quot; dataset and added region feature
bb_clean_eda2 = bb_clean %&gt;%
  mutate(Region = case_when(
    is.element(State, west) ~ &quot;West&quot;,
    is.element(State, midwest) ~ &quot;Midwest&quot;,
    is.element(State, southwest) ~ &quot;Southwest&quot;,
    is.element(State, southeast) ~ &quot;Southeast&quot;,
    is.element(State, northeast) ~ &quot;Northeast&quot;,
    is.element(State, hawaii_alaska) ~ &quot;Other&quot;
  ))

#AOV for ABV
fit_eda2_ABV = aov(ABV~Region, data=bb_clean_eda2)
summary(fit_eda2_ABV)</code></pre>
<pre><code>##               Df  Sum Sq   Mean Sq F value Pr(&gt;F)  
## Region         5 0.00215 0.0004303   2.346 0.0393 *
## Residuals   1399 0.25663 0.0001834                 
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
</div>
<div id="analsis-of-variance-between-regions" class="section level2">
<h2>Analsis of Variance between Regions</h2>
<div id="abv-analysis-of-variance" class="section level3">
<h3>ABV Analysis of Variance</h3>
<p>From the analysis of variance test there was weak evidence to suggest that at least two of the regions mean ABV are different from each other.(P = 0.0393).</p>
<pre class="r"><code># AOV for IBU
fit_eda2_IBU = aov(IBU~Region, data=bb_clean_eda2)
summary(fit_eda2_IBU)</code></pre>
<pre><code>##               Df Sum Sq Mean Sq F value   Pr(&gt;F)    
## Region         5  14341  2868.1   4.308 0.000681 ***
## Residuals   1399 931413   665.8                     
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
</div>
<div id="ibu-analysis-of-variance" class="section level3">
<h3>IBU Analysis of Variance</h3>
<p>From the analysis of variance test there was very strong evidence to suggest that at least two of the regions mean IBUs are different from each other. (P = 0.000681)</p>
<p>Since we have evidence to suggest there is a difference for both ABV and IBU we will proceed with a multi-comparison analysis of the regions to find which regions are statistically different from the others.</p>
</div>
</div>
<div id="multiple-comparison-of-abv-and-ibu" class="section level2">
<h2>Multiple Comparison of ABV and IBU</h2>
<div id="multiple-comparison-of-abv-between-regions" class="section level3">
<h3>Multiple Comparison of ABV between Regions</h3>
<pre class="r"><code>#Tukey multi comparison for ABV
TUK_EI_ABV = HSD.test(aov(lm(ABV ~ Region, data=bb_clean_eda2)), &quot;Region&quot;, group=F)
TUK_EI_ABV$comparison</code></pre>
<pre><code>##                          difference pvalue signif.          LCL          UCL
## Midwest - Northeast    0.0005279661 0.9977         -0.002837659 0.0038935915
## Midwest - Other        0.0039545768 0.5642         -0.002878070 0.0107872241
## Midwest - Southeast   -0.0011668123 0.9330         -0.004667945 0.0023343201
## Midwest - Southwest   -0.0013586100 0.9228         -0.005295065 0.0025778447
## Midwest - West        -0.0020026253 0.2652         -0.004667965 0.0006627138
## Northeast - Other      0.0034266106 0.7374         -0.003644656 0.0104978771
## Northeast - Southeast -0.0016947785 0.8245         -0.005641381 0.0022518237
## Northeast - Southwest -0.0018865762 0.8165         -0.006224020 0.0024508673
## Northeast - West      -0.0025305915 0.2215         -0.005758869 0.0006976857
## Other - Southeast     -0.0051213891 0.3158         -0.012258146 0.0020153681
## Other - Southwest     -0.0053131868 0.3091         -0.012673285 0.0020469118
## Other - West          -0.0059572021 0.1211         -0.012723250 0.0008088461
## Southeast - Southwest -0.0001917977 1.0000         -0.004635210 0.0042516143
## Southeast - West      -0.0008358130 0.9810         -0.004205126 0.0025334996
## Southwest - West      -0.0006440153 0.9968         -0.004463703 0.0031756725</code></pre>
<p>There is no statistically significant evidence to suggest that there is a difference in any of the populations. (P &gt; 0.05)</p>
</div>
<div id="multiple-comparison-of-ibu-between-regions" class="section level3">
<h3>Multiple Comparison of IBU between Regions</h3>
<pre class="r"><code>#Tukey multi comparison for IBU
TUK_EI_IBU = HSD.test(aov(lm(IBU ~ Region, data=bb_clean_eda2)), &quot;Region&quot;, group=F)
TUK_EI_IBU$comparison</code></pre>
<pre><code>##                       difference pvalue signif.        LCL        UCL
## Midwest - Northeast    -2.388083 0.8960          -8.799942  4.0237762
## Midwest - Other         2.533206 0.9937         -10.483683 15.5500948
## Midwest - Southeast    -4.826226 0.3065         -11.496240  1.8437879
## Midwest - Southwest    -1.040421 0.9987          -8.539768  6.4589265
## Midwest - West         -7.349071 0.0005     *** -12.426813 -2.2713279
## Northeast - Other       4.921289 0.9035          -8.550194 18.3927715
## Northeast - Southeast  -2.438143 0.9400          -9.956822  5.0805360
## Northeast - Southwest   1.347662 0.9973          -6.915610  9.6109339
## Northeast - West       -4.960988 0.1939         -11.111185  1.1892091
## Other - Southeast      -7.359432 0.6353         -20.955681  6.2368178
## Other - Southwest      -3.573626 0.9786         -17.595364 10.4481112
## Other - West           -9.882276 0.2440         -22.772287  3.0077349
## Southeast - Southwest   3.785805 0.7981          -4.679347 12.2509580
## Southeast - West       -2.522845 0.8725          -8.941728  3.8960394
## Southwest - West       -6.308650 0.1325         -13.585544  0.9682446</code></pre>
<p>There is strong evidence to suggest that there is a difference in the mean IBU between the Midwest and West regions.(P = 0.005). The other regions there was not enough evidence. (P &gt; 0.05).</p>
</div>
</div>
<div id="boxplot-of-ibu-for-the-west-and-midwest-regions" class="section level2">
<h2>Boxplot of IBU for the West and Midwest Regions</h2>
<pre class="r"><code>#View comparing just the Midwest and West
bb_clean_eda2 %&gt;% filter(Region == &quot;Midwest&quot; | Region == &quot;West&quot;) %&gt;%
  ggplot(aes(x=Region, y=IBU, fill=Region)) + geom_boxplot() +
  stat_summary(fun=mean, colour=&quot;darkred&quot;, geom=&quot;point&quot;, 
               shape=18, size=3, show.legend=FALSE) + 
  stat_summary(fun=mean, colour=&quot;red&quot;, geom=&quot;text&quot;, show.legend = FALSE, 
                vjust=-0.7, aes( label=round(..y.., digits=1))) + 
  ggtitle(&quot;Boxplot Comparison of West and Midwest Regions&quot;) + ylab(&quot;IBU&quot;)</code></pre>
<p><img src="case_study_01_files/figure-html/custom_eda_06-1.png" width="672" /></p>
<p>It’s not currently clear if this difference is practically significant but we know that there is a difference and this may be worth looking into further.</p>
</div>
</div>
<div id="additional-exploratory-data-analysis---german-beer-regions" class="section level1">
<h1>Additional Exploratory Data Analysis - German Beer Regions</h1>
<p>We would like to analyze potential locations for Budweiser to launch traditional German beer styles. We will plot a map of brewery locations that produce German beers, and identify regions or states that could be potential customers.</p>
<div id="exploring-german-beer-regions" class="section level2">
<h2>Exploring German Beer Regions</h2>
<p>A list of German beer styles was manually defined.</p>
<pre class="r"><code>german_beers &lt;- c(
  &#39;German Pilsener&#39;, 
  &#39;Munich Helles Lager&#39;, 
  &#39;Schwarzbier&#39;, 
  &#39;Hefeweizen&#39;, 
  &#39;Munich Dunkel Lager&#39;, 
  &#39;Radler&#39;, 
  &#39;Rauchbier&#39;, 
  &#39;Dunkelweizen&#39;, 
  &#39;Roggenbier&#39;, 
  &#39;Kristalweizen&#39;, 
  &#39;Keller Bier / Zwickel Bier&#39;
)</code></pre>
</div>
<div id="add-geolocation-data-to-breweries" class="section level2">
<h2>Add Geolocation Data to Breweries</h2>
<p>We can plot the brewery locations on a map if we join the city and state values and use the latitude and longitude from the “Cities” dataset.</p>
<pre class="r"><code># join geolocation to brewery data
geo_loc &lt;- left_join(bb, cities, by=c(&#39;City&#39;=&#39;CITY&#39;, &#39;State&#39;=&#39;STATE_CODE&#39;))</code></pre>
</div>
<div id="plot-a-map-of-breweries-that-brew-german-beers" class="section level2">
<h2>Plot a Map of Breweries that Brew German Beers</h2>
<p>From the analysis, we can see that the highlighted states in the Southeast region could be good candidates for marketing new German style beers.</p>
<pre class="r"><code># create vector of states to highlight
highlight_states &lt;- c(
  &#39;alabama&#39;,
  &#39;georgia&#39;,
  &#39;south carolina&#39;,
  &#39;tennessee&#39;,
  &#39;louisiana&#39;,
  &#39;mississippi&#39;,
  &#39;arkansas&#39;,
  &#39;oklahoma&#39;
)

# add a new column labeling German beers and save as variable
df_region &lt;- geo_loc %&gt;% 
  mutate(beer_region = ifelse(Style %in% german_beers, &#39;German&#39;, &#39;Others&#39;)) %&gt;%
  filter(!State %in% c(&#39;AK&#39;, &#39;HI&#39;)) %&gt;%
  arrange(desc(beer_region))

# create filter for German region only
df_de &lt;- df_region %&gt;%
  filter(beer_region == &#39;German&#39;)

# add geographical data for mapping
us_states &lt;- map(&quot;state&quot;, plot=FALSE, fill=TRUE) %&gt;%
  st_as_sf()

# select states to highlight
highlight &lt;- us_states %&gt;% filter(ID %in% highlight_states)

# create map
p &lt;- ggplot() +
  geom_sf(data=us_states, color=&#39;white&#39;, fill=&#39;lightgray&#39;) +
  geom_sf(data=highlight, color=&#39;white&#39;, fill=&#39;#DD1731&#39;) +
  # remove background and format text
  theme(
    plot.title = element_text(size=18, color=&#39;#DD1731&#39;),
    panel.background = element_blank(),
    panel.grid.major=element_blank(),
    panel.grid.minor=element_blank(),
    panel.border=element_blank(),
    axis.line=element_blank(),
    axis.text=element_blank(),
    axis.title=element_blank(),
    axis.ticks=element_blank()
  ) +
  labs(title=&#39;Breweries Serving German Style Beers&#39;)

# add the German beer breweries
p &lt;- p + geom_point(data=df_de, aes(x=CITY_LON, y=CITY_LAT), color=&#39;#2d3436&#39;,
                    size=1.5)

# print the map
p</code></pre>
<p><img src="case_study_01_files/figure-html/unnamed-chunk-4-1.png" width="672" /></p>
</div>
</div>




</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
